### PR TITLE
Add address sanitizer in CI and switch cpu build to release

### PR DESCRIPTION
**Pull request by Rombur**
Not ready to be merged yet but that's the only way to test the CI.

### CODE REVIEW

**Comment by Rombur** [comment]
retest this please

**Comment by Rombur** [comment]
Retest this please

**Comment by Rombur** [comment]
This is ready for review. The problem with the build system was because there is an @ in the name of the directory generated by jenkins. I now filter out the @ with a regex.

**Review by stvdwtt — APPROVED** [review]
Looks good to me.

**Pull request merged**
