### PR TITLE
Update copyright years

### PR DESCRIPTION
**Pull request by Rombur**
This simply update the years in the copyright.

### CODE REVIEW

**Review by stvdwtt — COMMENTED** [review]
This an incredibly small thing, but some of the files say 2016-2021 and some say 2017-2021. Is that intentional based on the age of some files?

**Comment by Rombur** [comment]
> Is that intentional based on the age of some files?

Yes, it is.

**Comment by stvdwtt** [comment]
Good to know -- I haven't properly dealt with copyright dates previously...

**Comment by Rombur** [comment]
> I haven't properly dealt with copyright dates previously...

I fixed it in this PR :)

**Pull request merged**
